- name: Install Docker (minimal playbook)
  hosts: docker_hosts
  become: yes
  vars:
    docker_apt_repo: "https://download.docker.com/linux/ubuntu"
    docker_gpg_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

  tasks:
    - name: Ensure prerequisite packages present
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.ansible.builtin.command:
        cmd: "install -m0755 -d /etc/apt/keyrings && curl -fsSL {{ docker_gpg_url }} -o /etc/apt/keyrings/docker.gpg && chmod a+r /etc/apt/keyrings/docker.gpg"
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] {{ docker_apt_repo }} {{ ansible_lsb.codename }} stable"
        state: present
        filename: docker

    - name: Update apt and install Docker packages
      apt:
        name: "{{ docker_packages }}"
        state: latest
        update_cache: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Ensure python docker package installed (for Ansible docker modules)
      pip:
        name: docker
        executable: pip3

    - name: Deploy daemon.json (optional - sets JSON log driver + max size)
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        owner: root
        mode: '0644'
      notify: Restart docker

  handlers:
    - name: Restart docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
